[[repos]]
repo = "local"

[[repos.hooks]]
id = "biome"
name = "Biome"
language = "system"
entry = "npm run check"
pass_filenames = false

[[repos.hooks]]
id = "typecheck"
name = "TypeScript"
language = "system"
entry = "npm run typecheck"
pass_filenames = false
